config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "locations#index"

  devise_for :users,
             controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new', as: :new_user_session
    delete 'sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  resources :locations, param: :code do
    get :open_now, on: :collection

    resources :timetables, only: [] do
      collection do
        get :exceptional_edit
        get :batch_edit
        post :batch_update
      end
    end
  end

  resource :admin, only: [:show]

  get 'api/v1/locations/open_now' => 'api/v1/locations#open_now'
  get 'api/v1/locations/:code' => 'api/v1/locations#open_hours'
end

app/views/admins/show.html.erb
<div class="row">
  <div class="col-sm-8">
    <div class="card mb-3">
      <div class="card-block">
        <div class="card-title">
          <h2 class="text-center">Editable Locations</h2>
        </div>
        <div class="card-text">
          <table class="table">
            <tbody>
              <% @locations.each do |lib| %>
                <% if can? :edit, lib %>
                  <tr>
                    <td><%= link_to lib.name, edit_location_path(lib.code) %></td>
                    <td><%= link_to 'Set Hours', exceptional_edit_location_timetables_path(lib.code)%></td>
                    <td><%= link_to 'Batch Edit Hours', batch_edit_location_timetables_path(lib.code)%></td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <div class="col-sm-4">
    <% if can? :create, Location %>
      <div class="card mb-3">
        <div class="card-block">
          <p class="card-text">
            <%= link_to '<i class="fa fa-plus" aria-hidden="true"></i> Add New Location'.html_safe, new_location_path %>
          </p>
        </div>
      </div>
    <% end %>

    <% if can? :create, User %>
      <div class="card mb-3">
        <div class="card-block">
          <p class="card-text">
            <%= link_to '<i class="fa fa-user-plus" aria-hidden="true"></i> Add User'.html_safe, new_user_path %>
          </p>
        </div>
      </div>
    <% end %>

    <% if can? :edit, User %>
      <div class="card mb-3">
        <div class="card-block">
          <p class="card-text">
            <%= link_to '<i class="fa fa-users" aria-hidden="true"></i> Manage Users'.html_safe, users_path %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>