config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "locations#index"

  devise_for :users,
             controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new', as: :new_user_session
    delete 'sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  resources :locations, param: :code do
    get :open_now, on: :collection

    resources :timetables, only: [] do
      collection do
        get :exceptional_edit
        get :batch_edit
        post :batch_update
      end
    end
  end

  resource :admin, only: [:show]

  get 'api/v1/locations/open_now' => 'api/v1/locations#open_now'
  get 'api/v1/locations/:code' => 'api/v1/locations#open_hours'
end

app/models/location.rb
class Location < ApplicationRecord
  validates :name, :code, presence: true, uniqueness: { case_sensitive: true }
  validate :primary_location_must_be_primary

  has_many :timetables
  has_many :access_points_locations
  has_many :access_points, through: :access_points_locations

  belongs_to :primary_location, class_name: 'Location', foreign_key: 'primary_location_id', optional: true
  accepts_nested_attributes_for :access_points

  # TODO: when a location is deleted any permissions related to that location should also be deleted

  def primary_location_must_be_primary
    if primary_location
      if primary
        errors.add :primary_location, "primary locations cannot have a primary location"
      end

      unless primary_location.primary == true
        errors.add :primary_location, "cannot assign non-primary location as primary location"
      end
    end
  end

  def self.attributes_protected_by_default
    [] # override ["id"]
  end

  # Note: To build an API response for a single date value,
  # call this method with both the start_date and
  # end_date set to the single date value.
  def build_api_response(start_date, end_date)
    if start_date > end_date
      raise RangeError.new("build_api_response: start_date is larger than end_date.")
    end

    # Note: date_range is a scope defined in timetable.rb

    # Old behavior : return nothing for non-existent timetables. Just the
    # following one-liner, in case want to revert back to that behavior
    # timetables.date_range(start_date,end_date).map {|t| t.api_response_hash}

    # New behavior: Instead of no-op for non-existent timetables, we want to return
    # a hash with default values for each non-existent timetable
    hash = timetables.date_range(start_date,end_date).map do |t|
      [t.date.strftime("%F"),  t.day_info_hash]
    end.to_h
    (start_date..end_date).map do |d|
      hash.fetch(d.strftime("%F"), Timetable.default_day_info_hash(d))
    end
  end
end

app/controllers/api/v1/locations_controller.rb
class Api::V1::LocationsController < Api::V1::BaseController
  skip_before_action :authenticate_user!, only: [:open_hours, :open_now]
  skip_load_and_authorize_resource only: [:open_hours, :open_now]
  before_action :add_cors_header, only: [:open_hours, :open_now]

  def open_hours
    begin
      location = Location.find_by! code: params[:code]
      if params[:date].eql? 'today' 
        start_date = Date.current
        end_date = Date.current
      elsif params[:date]
        start_date = Date.parse(params[:date])
        end_date = Date.parse(params[:date])
      else
        # Date#parse will raise an ArgumentError if problem with its argument
        start_date = Date.parse(params[:start_date])
        end_date = Date.parse(params[:end_date])
        raise RangeError, "start_date greater than end_date" if start_date > end_date
      end
      data_value = { location.code => location.build_api_response(start_date, end_date) }
      render json: { data: data_value }
    rescue ArgumentError => e
      render json: { error: { "msg" => "400: #{e.message}" }, data: nil } , status: 400
    rescue ActiveRecord::RecordNotFound => e
      render json: { error: { "msg" => "404: location not found" }, data: nil } , status: 404
    rescue RangeError => e
      render json: { error: { "msg" => "400: #{e.message}" }, data: nil } , status: 400
    end
  end

  def open_now
    @now = Time.current
    open_locations_hash = {}
    timetables_open_now.each do |t|
      open_locations_hash[t.location.code] = t.open_now_hash
    end
    data_value = open_locations_hash.empty?  ? nil :  open_locations_hash
    render json: { data: data_value }
  end

  # fcd1, 10/25/17: Following functionality is almost verbatim
  # the same code as found in all_open#LocationsController
  # Therefore, for now, this functionality was removed from #open_now
  # above and put in it's own method. This should help refactor in the
  # future if we decide to merge this method and all_open#LocationsController
  def timetables_open_now
    open_now = Timetable.where("open < ?" , @now)
      .where("close > ?" , @now)
      .where(closed: false)
      .where(tbd: false)
      .includes(:location)
    open_now.select do |t|
      pli = t.location.primary_location_id
      pli ? open_now.detect { |t2| t2.location_id == pli } : true
    end
  end

  def add_cors_header
    headers['Access-Control-Allow-Origin'] = '*'
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :load_location
  skip_before_action :load_location, only: [:index, :open_now, :new, :create]
  skip_before_action :authenticate_user!, only: [:index, :show, :open_now]
  skip_before_action :verify_authenticity_token, only: :show
  def index
    home_page = begin
      path = request.original_fullpath.split('?')[0]
      path.blank? or path == '/'
    end
    if home_page
      @locations = Location.where(front_page: true).where.not(code: 'all').where.not(suppress_display: true).includes(:access_points)
    else
      @locations = Location.where.not(code: 'all').where.not(suppress_display: true).includes(:access_points)
    end
    @locations = @locations.order(:name)
    @now = Time.current
    @open = all_open(home_page)
    @closed_location_ids_to_tomorrow_open_timetables = closed_location_ids_to_tomorrow_open_timetables(@open, home_page)
    render layout: "public"
  end

  def new
    authorize! :new, Location
    @location = Location.new
  end

  def edit
    authorize! :edit, @location
  end

  def create
    @location = Location.new(create_params)
    authorize! :create, @location
    if @location.save
      flash[:success] = "Location successfully created"
      redirect_to admin_url
    else
      error = @location.errors.full_messages.to_sentence
      flash[:error] = error
      render :new
    end
  end

  def update
    authorize! :update, @location
    clean_params = update_params
    clean_params.dig(:access_points)&.map! do |ap|
      ap.present? ? AccessPoint.find_or_create_by(id: ap.to_i) : nil
    end
    clean_params.dig(:access_points)&.compact!
    if @location.update(clean_params)
      flash[:success] = "Location successfully updated"
      redirect_to admin_url
    else
      error = @location.errors.full_messages.to_sentence
      flash[:error] = error
      render :edit
    end
  end

  def destroy
    authorize! :destroy, @location
  end

  def show
    unless @location && (current_user || !@location.suppress_display)
      respond_to do |format|
        format.html { render "errors/not_found", status: 404, layout: "public" }
        format.json { render json: {}, status: 404 }
      end
      return
    end
    @secondary_locations = Location.where(primary_location: @location).load
    @date = params[:date] ? Date.parse(params[:date]) : Date.current
    respond_to do |format|
      format.html { render layout: "public" }
      format.json { render json: @location.to_json }
      format.js do
        # this is support for a legacy API to be retired before v2
        schedule = Timetable.find_by(date: @date, location_id: @location.id)
        hours = schedule ? schedule.display_str : "TBD"
        hours.sub!('-','&mdash;')
        render js: "#{params[:callback]}({\"hours\":\"#{hours}\"})"
      end
    end
  end

  def open_now
    @now = Time.current
    @open = all_open
    render layout: "public"
  end

  def load_location
    @location = Location.find_by!(code: params['code'])
  end

  def all_open(home_page = false)
    all_open = Timetable.where("open < ?" , @now)
                     .where("close > ?" , @now)
                     .where(closed: false)
                     .where(tbd: false)
                     .includes(:location)
    all_open = all_open.where(locations: {front_page: true}) if home_page
    all_open = all_open.order('locations.name')
    all_open = all_open.where.not(locations: { code: 'all' })
    all_open = all_open.load
    all_open.select do |t|
      pli = t.location.primary_location_id
      pli ? all_open.detect { |t2| t2.location_id == pli } : true
    end
  end

  def closed_location_ids_to_tomorrow_open_timetables(open_location_timetables = all_open, home_page = false)
    open_location_ids = all_open.map { |timetable| timetable.location_id }
    closed_locations = Location.where.not(id: open_location_ids)

    tomorrow_open_timetables_for_closed = Timetable.where(location_id: closed_locations)
                    .where("open > ?" , @now)
                    .where("open < ?" , @now + 1.day)
                    .where(closed: false)
                    .where(tbd: false)
                    .order(:date) # make sure that next day appears first in sort order, in case we get two calendar dates in results
                    .includes(:location)
    tomorrow_open_timetables_for_closed = tomorrow_open_timetables_for_closed.where(locations: {front_page: true}) if home_page
    tomorrow_open_timetables_for_closed = tomorrow_open_timetables_for_closed.where.not(locations: {code: 'all'})
    closed_loc_ids_to_tomorrow_open_timetables = {}
    tomorrow_open_timetables_for_closed.each do |timetable|
      next if closed_loc_ids_to_tomorrow_open_timetables.key?(timetable.location_id)
      closed_loc_ids_to_tomorrow_open_timetables[timetable.location_id] = timetable
    end
    closed_loc_ids_to_tomorrow_open_timetables
  end

  private

  def create_params
    params.require(:location).permit(:name, :code, :comment, :comment_two, :url, :summary, :primary, :primary_location_id, :short_note, :short_note_url)
  end

  def update_params
    if current_user.administrator?
      params.require(:location).permit(:name, :code, :comment, :comment_two, :url, :summary, :primary, :primary_location_id, :front_page, :short_note, :short_note_url, :suppress_display, :wifi_connections_baseline, access_points: [])
    else
      params.require(:location).permit(:comment, :comment_two, :url, :summary, :short_note, :short_note_url)
    end
  end
end

app/views/locations/_location_form.html.erb
<div>
  <%= form_for(@location, url: @location.new_record? ? locations_path : location_path(@location.code)) do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <% if current_user.administrator? %>
        <%= f.text_field :name, :class => "form-control" %>
      <% else %>
        <p class="static-control-form"><%= @location.name %></p>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.label :code %>
      <% if @location.new_record? || current_user.administrator? %>
        <%= f.text_field :code, :class => "form-control" %>
      <% else %>
        <p class="static-control-form"><%= @location.code %></p>
      <% end %>
    </div>

    <div class="form-group">
      <h3>Location Display Options</h3>
        <% if current_user.administrator? %>
          <ul>
            <li class="form-check"><%= f.label(:suppress_display, class: ['form-check-label']) { f.check_box(:suppress_display, class: ['form-check-input']).safe_concat("Suppress Display") } %></li>
            <li class="form-check"><%= f.label(:front_page, class: ['form-check-label']) { f.check_box(:front_page, class: ['form-check-input']).safe_concat("Front Page") } %></li>
            <li class="form-check"><%= f.label(:primary, class: ['form-check-label']) { f.check_box(:primary, class: ['form-check-input']).safe_concat("Primary") } %></li>
          </ul>
          <div class="form-group">
            <%= f.label :primary_location %>
            <%= collection_select(:location, :primary_location_id, Location.where(primary: true), :id, :name, {include_blank: 'None'}) %>
          </div>
        <% else %>
          <ul>
            <% if @location.suppress_display %>
              <li><span class="warn static-control-form"><%= t("location.suppressed") %></span></li>
            <% end %>
            <li>Front Page: <%= (!!@location.front_page).to_s %></li>
            <li>Primary: <%= (!!@location.primary).to_s %></li>
            <% if @location.primary_location %>
              <li>Primary Location: <%= @location.primary_location.name %></li>
            <% end %>
          </ul>
        <% end %>
    </div>

    <div class="form-group">
      <%= f.label :url %>
      <%= f.text_field :url, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :comment %>
      <%= f.text_field :comment, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :comment_two %>
      <%= f.text_field :comment_two, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :short_note, 'Short Note (for API Administrators)' %>
      <%= f.text_field :short_note, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :short_note_url, 'Short Note URL (for API Administrators)' %>
      <%= f.text_field :short_note_url, :class => "form-control" %>
    </div>


    <div class="form-group">
      <h3>WiFi Configuration</h3>
      <div class="form-group">
        <%= f.label :wifi_connections_baseline, 'WiFi Connections Baseline Count' %>
        <%= f.text_field :wifi_connections_baseline, :class => "form-control" %>
      </div>
      <% current_aps = @location.access_point_ids.map(&:to_s) %>
      <%= access_point_checkboxes(Hours::WifiDensity.access_point_trees(@location), (1...).each, current_aps) %>
    </div>
    <%= f.submit :class => 'btn btn-primary btn-sm'%>
  <% end %>
</div>

app/views/locations/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <h2>Edit Location</h2>

    <%= render "location_form" %>
  </div>
</div>

app/views/locations/index.html.erb
<% wifi_data_available_for_at_least_one_location = false %>
<div id="home-toc">
  <h2 class="h4 text-uppercase text-center">Libraries Open Now</h2>
  <h3 class="small text-center">Click on a location for its full schedule.</h3>
  <ul class="lib-list">
    <% @locations.each do |location| %>
      <%-
          status = until_or_closed(location, @open)
          use_class = " is-closed" if status == 'CLOSED'
          use_class = " is-24" if status == 'OPEN'
       %>
       <%-
          if status == 'CLOSED'
            if @closed_location_ids_to_tomorrow_open_timetables.key?(location.id)
              next_open_timetable = @closed_location_ids_to_tomorrow_open_timetables[location.id]
              closed_location_next_open = "Next Open<br />#{next_open_timetable.date.strftime("%-m/%e")} #{next_open_timetable.open_time.strftime("%l:%M %P")} - #{next_open_timetable.close_time.strftime("%l:%M %P")}"
            else
              closed_location_next_open = "Not open within the next 24 hours."
            end
          end
       %>
      <li class="location-item">
        <span class="closes-at pull-right<%= use_class %>">
          <% if status == 'CLOSED' %>
            <span data-toggle="tooltip" data-placement="top" title="<%= closed_location_next_open %>">
              <%= status %>
            </span>
          <% else %>
            <%= status %>
          <% end %>
        </span>
        <%- if (status != 'CLOSED' || Rails.env.development?) && (density_percentage = Hours::WifiDensity.percentage_for(location)) %>
          <span class="density-percentage pull-right"><span class="fal fa-signal"></span> <%= density_percentage %>%</span>
          <%- wifi_data_available_for_at_least_one_location = true %>
        <%- end %>
        <%= link_to location.name, location_path(location.code) %>
      </li>
    <% end %>
  </ul>
  <%- if wifi_data_available_for_at_least_one_location %>
    <p id="wifi_usage_data_statement" class="mt-3 trajanpro text-center">
      <span class="fal fa-signal"></span> Current WiFi usage data. Data provided by CUIT. <a href="https://library.columbia.edu/using-libraries/study-spaces/density-info.html">More details &amp; privacy information.</a>
    </p>
  <%- end %>
</div>

app/views/locations/new.html.erb
<div>
  <h2>Add a Location</h2>

  <%= render "location_form" %>
</div>

app/views/locations/open_now.html.erb
<h2 class="lead text-center">Study Spaces Open Now</h2>
<div class="well well-sm text-center"> <%= @now.strftime('%B %e, %Y') %></div>
<ul class="lib-list">
  <% @open.each do |timetable| %>
  <li class="location-item">
    <span class="closes-at pull-right">Until <%= timetable.close_time.strftime("%l:%M %P") %></span>
    <%= link_to timetable.location.name, location_path(timetable.location.code) %>
  </li>
  <% end %>
</ul>

app/views/locations/show.html.erb
<div class="location row">

    <div class="col-md-12">
      <h2 class="location-name"><%= link_to @location.name, @location.url %></h2>
      <div class="location-primary-comment">
        <% if @location.suppress_display %>
          <p class="warn"><%= t("location.suppressed") %></p>
        <% end %>
        <% if @location.primary_location %>
          <p>Check hours for: <strong class="text-center"><%= link_to @location.primary_location.name, location_path(@location.primary_location.code) %></strong></p>
        <% end %>
        <%= @location.comment.html_safe if @location.comment %>
      </div>
    </div>

    <%= render "timetables/timetable" %>
    <%= render "timetables/secondaries" %>

</div>

<div class="row">
    <div class="col-md-12">
      <div class="location-secondary-comment">
        <%= @location.comment_two %>
      </div>
    </div>
</div>